### PR TITLE
mod update

### PR DESCRIPTION
**Pull request by CanInBad**

### CODE REVIEW

**Comment by CanInBad** [comment]
I will add 2 more mods, just saw them

**Comment by Alexofp** [comment]
Remove hypnokink mod while you're at it x3

**Comment by CanInBad** [comment]
is done I hope

**Comment by Alexofp** [comment]
One of the preivew images gotten smaller but nothing changed?

**Comment by CanInBad** [comment]
> One of the preivew images gotten smaller but nothing changed?

I downloaded new one from discord, I don't know if its smaller though

**Comment by Alexofp** [comment]
Looking at the diff, its the same. Better change it back yeah I think

**Comment by Alexofp** [comment]
Should I merge? x3

**Comment by CanInBad** [comment]
after your hotfix

**Comment by Alexofp** [comment]
Thank you very much <3

**Pull request merged**
